name: Build Application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "21 1 * * 1-5"
  workflow_dispatch: # allow manual trigger
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-ubuntu-binary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Build exe
        run: |
          pyinstaller FontraPak.spec -y

      - name: Run tests
        run: |
          pytest

      - name: Storing Ubuntu Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FontraPakUbuntu
          path: ./dist/*

  upload-to-page:
    runs-on: ubuntu-latest
    needs: [build-ubuntu-binary ]
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Retrieve Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifact

      - name: Zip Ubuntu Artifact
        run: |
          cd ./downloaded-artifact/FontraPakUbuntu
          zip -q FontraPakUbuntu.zip "Fontra Pak"

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./downloaded-artifact

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fontra-Pak
          path: ./downloaded-artifact
        outputs:
          zip_name: FontraPakUbuntu
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
